AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda to upload MIP balance CSV files to FloQast via SFTP.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: "lambda-finops-floqast-sftp"
    Description: "A GH template for quickly starting a new AWS lambda project."
    Author: "Sage-Bionetworks"
    SpdxLicenseId: "Apache-2.0"
    # paths are relative to .aws-sam/build directory
    LicenseUrl: "LICENSE"
    ReadmeUrl: "README.md"
    Labels: ["serverless", "template", "github", "quick-start"]
    HomePageUrl: "https://github.com/Sage-Bionetworks-IT/lambda-finops-floqast-sftp"
    SemanticVersion: "0.0.3"
    SourceCodeUrl: "https://github.com/Sage-Bionetworks-IT/lambda-finops-floqast-sftp/tree/0.0.3"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  Schedule:
    Description: >-
      Schedule to execute the lambda, can be a rate or a cron schedule. Format at
      https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
    Type: String
    Default: cron(0 4 * * ? *)  # Run at 8pm PDT (4am UTC)
    ConstraintDescription: "Use schedule format: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html"

Resources:
  FloQastSftpFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: floqast_sftp/app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt FunctionRole.Arn
      Events:
        Schedule:
          # More info about Event Source:
          # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
            # JSON data passed to the lambda function as 'event',
            # The resource types need to match `ResourceTypeFilters` at
            # https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/org-formation/090-systems-manager/patch-resource-group.yaml
            Input: |-
              {
                "ssm_secret_prefix": "/floqast-sftp",
                "period_count": "1",
              }

  FunctionRole:   # execute lambda function with this role
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FloQastSftpFunctionArn:
    Description: "FloQast SFTP Lambda Function ARN"
    Value: !GetAtt FloQastSftpFunction.Arn
  FloQastSftpFunctionRoleArn:
    Description: "Implicit IAM Role created for FloQast SFTP function"
    Value: !GetAtt FunctionRole.Arn
